# -*- coding: utf-8 -*-
"""Cleaning_Train_Evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yj854cIWqXxdQchbfHLslyBB2vZo6XWv
"""

!pip install nltk

import nltk
nltk.download('stopwords')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer


# Load the dataset
df = pd.read_csv(
    'news-article-categories.csv',
    engine='python',
    on_bad_lines='skip'
)


print("--- Dataset Info ---")
print(df.info())
print("\n--- First 5 Rows ---")
print(df.head())

# Check for missing values
print("\n--- Missing Values ---")
print(df.isnull().sum())

# Check for duplicates
print(f"\nDuplicate rows before cleaning: {df.duplicated().sum()}")

# ==========================================
# 2. PREPROCESSING
# ==========================================

# A. Data Cleaning
# ----------------
# Drop duplicates to prevent data leakage
df.drop_duplicates(inplace=True)

# Drop rows with missing values (if any)
df.dropna(inplace=True)

# Text Cleaning Function
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def clean_text(text):
    if not isinstance(text, str):
        return ""
    # 1. Lowercase
    text = text.lower()
    # 2. Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # 3. Simple Trim
    return text.strip()

# Apply cleaning to 'body' and 'title' columns by combining
df['text_combined'] = df['title'] + " " + df['body']
df['clean_text'] = df['text_combined'].apply(clean_text)

print("\n--- Data After Cleaning ---")
print(df[['category', 'clean_text']].head())

# B. Data Transformation
# ----------------------
# Label Encoding (Converting categories)
label_encoder = LabelEncoder()
df['category_encoded'] = label_encoder.fit_transform(df['category'])

# Display the mapping
category_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print("\n--- Full Category Mapping ---")
for category, code in category_mapping.items():
    print(f"{category}: {code}")

# Feature Scaling/Vectorization (TF-IDF)
# limit to 5000 features to keep dimensionality manageable for the mini project
# add stop_words='english' here to handle the common words automatically
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
X = tfidf.fit_transform(df['clean_text']).toarray()
y = df['category_encoded']

print(f"\nShape of Feature Matrix (X): {X.shape}")
print(f"Shape of Target Vector (y): {y.shape}")

# ==========================================
# 3. VISUALIZATION
# ==========================================

# Plot 1: Dataset Distribution
plt.figure(figsize=(12, 6))
sns.countplot(y=df['category'], order=df['category'].value_counts().index, hue=df['category'], palette='viridis', legend=False)
plt.title('Distribution of News Articles per Category')
plt.xlabel('Number of Articles')
plt.ylabel('Category')
plt.tight_layout()
plt.show()

# Plot 2: Text Length Distribution (Before vs After Preprocessing)
df['original_len'] = df['text_combined'].apply(len)
df['clean_len'] = df['clean_text'].apply(len)

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.histplot(df['original_len'], bins=50, ax=axes[0], color='blue')
axes[0].set_title('Original Text Length Distribution')
axes[0].set_xlabel('Length (characters)')

sns.histplot(df['clean_len'], bins=50, ax=axes[1], color='green')
axes[1].set_title('Cleaned Text Length Distribution')
axes[1].set_xlabel('Length (characters)')

plt.show()

# Save cleaned dataset
df.to_csv('cleaned_news_dataset.csv', index=False)

import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Load the cleaned file from Person 1
df = pd.read_csv('cleaned_news_dataset.csv')

# 2. Define Features (X) and Labels (y)
X = df['clean_text'].astype(str)  # The text content
y = df['category_encoded']       # The numeric category ID

# 3. Split: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

# Create a 'Pipeline' to bundle the text processing and the model together
# This is crucial for Person 3 to use the model in the UI easily.
model_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000)), # Transform text to numbers
    ('clf', LinearSVC(C=1.0, dual=False))          # Hyperparameter: C=1.0 (Regularization)
])

# Train the model
model_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Generate predictions on the test set
y_pred = model_pipeline.predict(X_test)

# 1. Generate the Metrics Table
report = classification_report(y_test, y_pred)
print(report)

# 2. Generate the Confusion Matrix (Required Visualization)
fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax, cmap='Blues')
plt.title("Confusion Matrix: Linear SVM")
plt.savefig('confusion_matrix.png') # Give this image to Person 3 for the dashboard